### ISSUE TITLE
Error when using multi-gpu

### ISSUE THREAD

**Issue by Lin-Yijie** [Thinklab-SJTU/ThinkMatch#35]
Hi Runzhong. There still exists a multi-gpu problem. When running ngmv2 with 2 gpu (e.g., vgg16_ngmv2_voc.yaml),

```
Traceback (most recent call last):
  File "/home/simon/Code/ThinkMatch-master/train_eval.py", line 331, in <module>
    xls_wb=wb)
  File "/home/simon/Code/ThinkMatch-master/train_eval.py", line 90, in train_eval_model
    outputs = model(inputs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/Code/ThinkMatch-master/models/NGM/model_v2.py", line 96, in forward
    graph = self.message_pass_node_features(graph)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/Code/ThinkMatch-master/models/BBGM/sconv_archs.py", line 47, in forward
    result = self.mp_network(graph)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/Code/ThinkMatch-master/models/BBGM/sconv_archs.py", line 33, in forward
    xs += [F.relu(conv(xs[-1], edge_index, edge_attr))]
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch_geometric/nn/conv/spline_conv.py", line 126, in forward
    out += torch.matmul(x_r, self.root)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`


Process finished with exit code 1

```

**Comment by rogerwwww** [comment]
Hi, it seems to be an issue with ``spline_conv`` from ``torch_geometric``, and it may take some non-trivial effort to fix it. We will sincerely appreciate it if anyone could help us to look into this issue and provide us with any possible insights.

Currently, we recommend running with a single GPU. For other models that do not involve the ``spline_conv`` module, they seem to work just fine with multi-GPU.

**Comment by Lin-Yijie** [comment]
Thanks~
